name: Clang Format Fixer
on: push
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/clang-format-fix'
    steps:
    - name: Clang Code Formatter
      uses: ivanludvig/clang-format-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}