name: clang-format-fixer
on: push
jobs:
  lint:
    name: clang-format-fixer
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/clang-format-fixer'
    steps:
      - uses: actions/checkout@v2
      - uses: amahanna/clang-format-fixer@v1.0.3
        with:
          sources: "src/*.cpp,src/*.h"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}