name: clang-format-fixer
on: push
jobs:
  lint:
    name: clang-format-fixer
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/clang-format-fix'
    steps:
    - name: clang-format-fixer
      uses: amahanna/clang-format-fixer@v0.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
